name: Build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build x64 Release
        shell: pwsh
        run: .\build.ps1 -Configuration Release
